Feature/MP-9
varya-kot/mambet-pages pull request #16
Opened 2024-04-16 13:05 UTC by yanmayak

Completed first and second endpoint of issue, need reviev of POST /api/v1/articles to complete the task
@ArtemGet @varya-kot

2024-04-16 16:22 UTC, ArtemGet requested changes
PUT /api/v1/articles/{id} is missing

2024-04-16 16:22 UTC, ArtemGet commented on src/main/java/ru/mambetpages/controller/ArticleController.java
> +        firstArticle.setTags(List.of("Тег первой статьи", "Еще один тег первой статьи", "Третий тег первой статьи", "Последний тег первой статьи"));
use propper formatting:
https://www.yegor256.com/2014/10/23/paired-brackets-notation.html

2024-04-16 16:22 UTC, ArtemGet commented on src/main/java/ru/mambetpages/dto/PostArticleDto.java
> +    private String title;
title, content and tags should not be empty or null. 
Just add @Valid to the controller's attributes and other validation annotations to the DTO's attributes.
 
see this article https://www.baeldung.com/spring-boot-bean-validation

2024-04-17 09:09 UTC, varya-kot requested changes

2024-04-17 09:09 UTC, varya-kot commented on src/main/java/ru/mambetpages/controller/ArticleController.java
> +        PostArticleDto publishArticle = new PostArticleDto();
This method should return 201 status code with path to suitable GET method , without body 
see http://www.java2s.com/example/java-api/org/springframework/http/responseentity/created-1-2.html

2024-04-17 09:09 UTC, varya-kot commented on src/main/java/ru/mambetpages/controller/ArticleController.java
> +    public PostArticleDto postArticle(@RequestBody PostArticleDto articleDto) {
For future, return from methods only Get...Dto

2024-04-18 14:53 UTC, varya-kot requested changes

2024-04-18 14:53 UTC, VaryaGet commented on src/main/java/ru/mambetpages/dto/PostArticleDto.java
> +public class PostArticleDto {
rename ArticlePostDto

2024-04-18 14:53 UTC, VaryaGet commented on src/main/java/ru/mambetpages/dto/ArticleGetShortDto.java
> -public class GetArticleShortDto {
rename ArticleShortGetDto

2024-04-18 16:40 UTC, VaryaGet approved these changes

2024-04-18 20:11 UTC, ArtemGet approved these changes

2024-04-18 20:11 UTC, merged