Feature/mp-11
varya-kot/mambet-pages pull request #19
Opened 2024-04-24 11:21 UTC by yanmayak

Completed the task, added email service and tested on host smtp.yandex.ru. Added some test files to .gitignore, added dependency to pom.xml

2024-04-24 11:52 UTC, ivamijava approved these changes
K A I F

2024-04-24 12:08 UTC, varya-kot requested changes

2024-04-24 12:08 UTC, VaryaGet commented on .gitignore
> +ru/mambetpages/service/TestController.java
Remove "ru/mambetpages/service/TestController.java" from gitignore, and just don't add to commit this file

2024-04-24 12:14 UTC, yanmayak commented on .gitignore
> +ru/mambetpages/service/TestController.java
done

2024-04-24 12:17 UTC, varya-kot approved these changes

2024-04-24 15:54 UTC, ArtemGet requested changes

2024-04-24 15:54 UTC, ArtemGet commented on src/main/resources/application.yaml
> +    username:
Better use arguments, like ${USERNAME} to all attributes

2024-04-25 17:11 UTC, ArtemGet approved these changes

2024-04-25 18:06 UTC, merged