MP-4
varya-kot/mambet-pages pull request #20
Opened 2024-04-26 11:10 UTC by ivamijava

Added entities and connected database
Closes #6

2024-04-26 16:29 UTC, varya-kot requested changes

2024-04-26 16:29 UTC, varya-kot commented on src/main/java/ru/mambetpages/entity/User.java
> +    @Column(name = "hashedPassword", nullable = false)
Rename all needed columns in snake case

2024-04-26 16:29 UTC, varya-kot commented on src/main/java/ru/mambetpages/repository/UserProfileRepository.java
> +
@Repository

2024-04-26 16:29 UTC, varya-kot commented on src/main/java/ru/mambetpages/repository/UserRepository.java
> +
@Repository

2024-04-26 17:08 UTC, ivamijava commented on src/main/java/ru/mambetpages/entity/User.java
> +    @Column(name = "hashedPassword", nullable = false)
Done!

2024-04-26 17:09 UTC, ivamijava commented on src/main/java/ru/mambetpages/repository/UserProfileRepository.java
> +
Done!

2024-04-26 17:09 UTC, ivamijava commented on src/main/java/ru/mambetpages/repository/UserRepository.java
> +
Done!

2024-04-27 16:52 UTC, varya-kot approved these changes

2024-04-27 16:56 UTC, ArtemGet requested changes

2024-04-27 16:56 UTC, ArtemGet commented on src/main/java/ru/mambetpages/repository/UserProfileRepository.java
> +
Redundant annotation, remove it

2024-04-27 16:56 UTC, ArtemGet commented on src/main/java/ru/mambetpages/repository/UserRepository.java
> +
Redundant annotation, remove it

2024-04-27 16:56 UTC, ArtemGet commented on src/main/resources/application.yaml
> +    driver-class-name: org.postgresql.Driver
Use parameters like ${PG_USERNAME:}

2024-04-27 16:56 UTC, ArtemGet commented on src/main/resources/application.yaml
> +    show-sql: true
default false

2024-04-27 17:49 UTC, ivamijava commented on src/main/resources/application.yaml
> +    driver-class-name: org.postgresql.Driver
Done!

2024-04-27 17:49 UTC, ivamijava commented on src/main/resources/application.yaml
> +    show-sql: true
Done!

2024-04-27 17:56 UTC, ArtemGet approved these changes

2024-04-27 17:57 UTC, merged